[package]
name = "punt_the_weak"
version = "0.1.0"
authors = ["eraiser <krotttendorfer@hotmail.de>"]
edition = "2018"

[dependencies]
gl = "0.12.0"
glutin = "0.22.0-alpha1"
cgmath = "0.17.0"
image = "0.22.0"
collada = "0.11.0"
rayon = "1.2.0"
rand = "0.7.2"
